/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigoBarrasV1;

/**
 *
 * @author loroz
 */


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Formatter;
//import org.apache.log4j.Logger;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ventana extends javax.swing.JFrame {
DefaultTableModel modelo = new DefaultTableModel();
        int nUltimo;
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] titulo= new String[]{"CÓDIGO DE BARRAS"};
        modelo.setColumnIdentifiers(titulo);
        jTable1.setModel(modelo);   
        desabilitar1();
    }

    
    
    public void desabilitar1(){
        jButtonGenerar.setEnabled(true);
        jComboBoxCantidad.setEnabled(true);
        jComboBoxCantidad.setSelectedIndex(0);
        jTable1.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
        for (int i = 0; i < jTable1.getRowCount(); i++) {
        modelo.removeRow(i);
        i-=1;
        }
    }
    
    public  void desabilitar2(){
        jButtonGenerar.setEnabled(false);
        jComboBoxCantidad.setEnabled(false);
        jTable1.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonImprimir.setEnabled(true);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCantidad = new javax.swing.JLabel();
        jComboBoxCantidad = new javax.swing.JComboBox<>();
        jButtonGenerar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("CANTIDAD DE ETIQUETAS:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));
        jComboBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 50, -1));

        jButtonGenerar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGenerar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGenerar.setForeground(new java.awt.Color(44, 72, 112));
        jButtonGenerar.setText("Mostar Códigos de barras");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 60, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 290, 130));

        jButtonImprimir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(44, 72, 112));
        jButtonImprimir.setText("IMPRIMIR");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(44, 72, 112));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-wallpaper-7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        // TODO add your handling code here:
        try {
            FileReader lector = new FileReader("numero.txt");
            BufferedReader BR =new BufferedReader(lector);
            String cadena=BR.readLine();

            int numero=Integer.parseInt(cadena);
            int dato=(Integer)jComboBoxCantidad.getSelectedIndex();
            if (dato==0) {
                JOptionPane.showMessageDialog(rootPane, "Selecciona una cantidad diferente de 0");
            } else {

                for (int i =++numero; i < (dato+numero); i++) {
                    //iint nuevo=i;
                    Formatter fmt = new Formatter();
                    modelo.addRow(new Object[]{fmt.format("%04d",i)});

                }
                desabilitar2();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
        int i= JOptionPane.showConfirmDialog(null, "Realmente deseas imprimir estas etiquetas", "Impresion de Etiquetas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(i==0){
            try {
                int valor=jTable1.getRowCount();//valor es el valor de todas la s columnas
                //Object hola=jTable1.getValueAt(--valor, NORMAL);
                // System.out.println(hola);
                for (int j = 0; j < valor; j++) {
                    Formatter fmt = new Formatter();
                    modelo.addRow(new Object[]{fmt.format("%04d",i)});
                    Object hola=jTable1.getValueAt(j, NORMAL);
                    String s = hola.toString();
                    ImprimeEtiquetas imprime = new ImprimeEtiquetas();
                    imprime.imprimeEtiqueta(s);

                }
                File fichero = new File("numero.txt");
                fichero.delete();

                Object hola=jTable1.getValueAt(--valor, NORMAL);
                String s = hola.toString();
                try {
                    FileWriter ficheroN = new FileWriter("numero.txt");
                    ficheroN.write(s);
                    ficheroN.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                desabilitar1();
                //System.out.println(valor);
                //

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Se Ha Cancelado La IMPRESION");
            desabilitar1();
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here
        JOptionPane.showMessageDialog(rootPane, "Se Ha Cancelado La OPERACION");
        desabilitar1();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCantidadActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar(); 
        int k=(int)evt.getKeyChar();
        
                if(Character.isLetter(validar)||k==64) { 
                getToolkit().beep(); 
               
                evt.consume(); 
               
                JOptionPane.showMessageDialog(rootPane, "ingresa solo numeros");
                }
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JComboBox<String> jComboBoxCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
